### ISSUE TITLE
should call finishUpdateItems to finalize updateItems

### ISSUE THREAD

**Issue by t9md** [lettertwo/atom-narrow-provider-diagnostics#1]
I noticed this from GIF, where updating indicator (`x` icon) remain `running` state.

This is because `ProviderBase.protototype.finishUpdateItems` is not called.
Updating items must be finalized to notify narrow-ui to finish updating.

Basically you have two pattern to finalize

- Option-1:
  - `finishUpdateItems(items)`: Use this if you update items in single response against request from UI.

- Option-2:
  - `updateItems(items)`: You can update(render) items multiple times against single request.
  - `finishUpdateItems()`: Then finalize with empty arg.

Why narrow provide option-2 is, `search` provider collect items on each `data` event of event emitter which is emitted multiple-time.
So when you search `foo`, the result is updated separately on each `data` event.
This prevent big items consume huge heap memory and blocking event-loop long-time while preparing new item-list on UI.

**Comment by lettertwo** [comment]
Thanks for checking the provider out!

I'm trying to figure out the right way to sync narrow UI updates with the diagnostics service updates, but i haven't quite figured it out yet. If you don't mind, i have a few questions about this:

1. after `finishUpdateItems()`, can i `updateItems()` again?

2. the Diagnostics service [pushes updates] to the narrow provider; do you have a recommendation for triggering narrow UI updates in this scenario? So far i've come up with [this hack].

[pushes updates]: https://github.com/lettertwo/atom-narrow-provider-diagnostics/blob/d7bfa44e2602ab8dfa121c1ccee7550958eb84c9/lib/createDiagnosticsProvider.js#L57
[this hack]: https://github.com/lettertwo/atom-narrow-provider-diagnostics/blob/d7bfa44e2602ab8dfa121c1ccee7550958eb84c9/lib/createDiagnosticsProvider.js#L26-L30

**Comment by t9md** [comment]
> after finishUpdateItems(), can i updateItems() again?

Whole flow is this

1. Type something on UI, that trigger `ui.refresh`
2. it eventually call `provider.getItems`
3. in provider's `getItem`,  send items to ui by `updateItems(items)`, then finalize `finishUpdateItems()`, `finishUpdateItems(items)` is shorthand of update then finish.

Each time, ui call `ui.refresh()`, `provider.getItems` is called unless it can use cached(by ui) items.
So while narrow-ui is opened, narrow is repeating 1-3 flow, on each trigger of `ui.refresh`

> the Diagnostics service pushes updates to the narrow provider; do you have a recommendation for triggering narrow UI updates in this scenario? So far i've come up with this hack.

Humm, it's difficult, you can manually fire `ui.refresh(force: true)` from provider by `provider.ui.refresh(force: true)`.

So, if you can subscribe event to update diagnostics push, then fire `provider.ui.refresh`?

Also refer narrow bundled core-providers to get some ideas.
